version: "3"
services:
  betting-feed-app-test:
    build:
      context: .
      dockerfile: "./infrastructure/docker/dev-test.Dockerfile"
    volumes:
      - "./:/betting-feed"
      - go_pkgs:/go/pkg
    ports:
      - 8080:8080
      - 2345:2345
    env_file:
      - .test.env
    environment:
      POSTGRES_DB: siimpl_esports_db_test
      POSTGRES_HOST: betting-feed-db-test
    depends_on:
      - betting-feed-db-test
  betting-feed-db-test:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - "./postgresql.conf:/var/lib/postgresql/data/postgresql.conf"
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: siimpl_dba
      POSTGRES_DB: siimpl_esports_db_test
volumes:
  go_pkgs: {}
