ALTER TABLE matches ALTER COLUMN is_autogenerated SET DEFAULT FALSE;
UPDATE matches SET is_autogenerated = FALSE WHERE is_autogenerated IS NULL;
ALTER TABLE matches ALTER COLUMN is_autogenerated SET NOT NULL;
