CREATE TABLE IF NOT EXISTS pool_defaults (
  id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  leg_count DECIMAL,
  game TEXT,
  TYPE TEXT,
  guarantee DECIMAL,
  carry_in DECIMAL,
  allocation DECIMAL,
  unit_value DECIMAL,
  min_unit_per_line DECIMAL,
  max_unit_per_line DECIMAL,
  min_unit_per_ticket DECIMAL,
  max_unit_per_ticket DECIMAL,
  currency TEXT,
  note TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS pool_defaults_uniqueness_on_legcount_game_type
  ON pool_defaults USING btree(leg_count, game, TYPE);

INSERT INTO pool_defaults (leg_count, game, type, guarantee, carry_in, allocation, unit_value, min_unit_per_line, max_unit_per_line, min_unit_per_ticket, max_unit_per_ticket, currency, note)
VALUES
 (4, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'H2H', 200, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'H2H', 500, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (8, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'H2H', 1000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'H2H', 2000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (4, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'OVER_UNDER', 200, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'OVER_UNDER', 500, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (8, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'OVER_UNDER', 1000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'OVER_UNDER', 2000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'FANTASY', 5000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'FANTASY', 10000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (4, 'DOTA_2', 'H2H', 200, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'DOTA_2', 'H2H', 500, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (8, 'DOTA_2', 'H2H', 1000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'DOTA_2', 'H2H', 2000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (4, 'DOTA_2', 'OVER_UNDER', 200, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'DOTA_2', 'OVER_UNDER', 500, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (8, 'DOTA_2', 'OVER_UNDER', 1000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'DOTA_2', 'OVER_UNDER', 2000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'DOTA_2', 'FANTASY', 5000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'DOTA_2', 'FANTASY', 10000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (4, 'LEAGUE_OF_LEGENDS', 'H2H', 200, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'LEAGUE_OF_LEGENDS', 'H2H', 500, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (8, 'LEAGUE_OF_LEGENDS', 'H2H', 1000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'LEAGUE_OF_LEGENDS', 'H2H', 2000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (4, 'LEAGUE_OF_LEGENDS', 'OVER_UNDER', 200, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'LEAGUE_OF_LEGENDS', 'OVER_UNDER', 500, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (8, 'LEAGUE_OF_LEGENDS', 'OVER_UNDER', 1000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'LEAGUE_OF_LEGENDS', 'OVER_UNDER', 2000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (6, 'LEAGUE_OF_LEGENDS', 'FANTASY', 5000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default'),
 (10, 'LEAGUE_OF_LEGENDS', 'FANTASY', 10000, 0, 1, 100, 1, 1, 1, 500000000, 'STR', 'autogenerated default')
;

