CREATE TABLE IF NOT EXISTS over_under_defaults (
  id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
  game TEXT NOT NULL,
  match_format TEXT NOT NULL,
  even_threshold DECIMAL NOT NULL,
  favored_threshold DECIMAL NOT NULL,
  note TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS over_under_defaults_uniqueness_on_game_match_format
  ON over_under_defaults USING btree(game, match_format);

INSERT INTO over_under_defaults (game, match_format, even_threshold, favored_threshold, note)
VALUES
 ('DOTA_2', 'bo2', 94.5, 47.5, 'autogenerated default'),
 ('DOTA_2', 'bo3', 141.5, 94.5, 'autogenerated default'),
 ('DOTA_2', 'bo5', 188.5, 141.5, 'autogenerated default'),
 ('COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'bo2', 320.5, 160.5, 'autogenerated default'),
 ('COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'bo3', 480.5, 320.5, 'autogenerated default'),
 ('COUNTER_STRIKE_GLOBAL_OFFENSIVE', 'bo5', 800.5, 640.5, 'autogenerated default'),
 ('LEAGUE_OF_LEGENDS', 'bo2', 49.5, 24.5, 'autogenerated default'),
 ('LEAGUE_OF_LEGENDS', 'bo3', 73.5, 49.5, 'autogenerated default'),
 ('LEAGUE_OF_LEGENDS', 'bo5', 122.5, 98.5, 'autogenerated default')
;
