CREATE TABLE IF NOT EXISTS events (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    external_id TEXT,
    name TEXT,
    type TEXT,
    is_active BOOLEAN,
    is_autogenerated BOOLEAN,
    logo TEXT,
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    game TEXT,
    UNIQUE (game, external_id)
);

CREATE TABLE IF NOT EXISTS matches (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    external_id TEXT,
    name TEXT,
    description TEXT,
    is_active BOOLEAN,
    is_autogenerated BOOLEAN,
    team_scores JSONB,
    team_win_probabilities JSONB,
    statistics JSONB,
    status TEXT,
    event_id UUID REFERENCES events (id) MATCH FULL ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE,
    event_stage TEXT,
    start_time TIMESTAMP WITH TIME ZONE,
    UNIQUE (event_id, external_id)
);

CREATE TABLE IF NOT EXISTS teams (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    external_id TEXT,
    name TEXT,
    logo TEXT,
    match_id UUID REFERENCES matches (id) MATCH FULL ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE,
    UNIQUE (match_id, external_id)
);

CREATE TABLE IF NOT EXISTS players (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    external_id TEXT,
    name TEXT,
    nickname TEXT,
    team_id UUID REFERENCES teams (id) MATCH FULL ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE,
    UNIQUE (team_id, external_id)
);

CREATE TABLE IF NOT EXISTS pools (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    name TEXT,
    TYPE TEXT,
    is_active BOOLEAN,
    is_autogenerated BOOLEAN,
    last_sync_time TIMESTAMP WITH TIME ZONE,
    game TEXT,
    synced_colossus_status TEXT
);

CREATE TABLE IF NOT EXISTS legs (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    last_sync_time TIMESTAMP WITH TIME ZONE,
    synced_colossus_status TEXT,
    match_id UUID REFERENCES matches (id) MATCH FULL ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE,
    pool_id UUID REFERENCES pools (id) MATCH FULL ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE,
    UNIQUE (pool_id, match_id)
);

CREATE TABLE IF NOT EXISTS users (
    id UUID NOT NULL PRIMARY KEY DEFAULT uuid_generate_v4(),
    email TEXT,
    PASSWORD BYTEA,
    token TEXT
);
