DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS legs;
DROP TABLE IF EXISTS pools;
DROP TABLE IF EXISTS players;
DROP TABLE IF EXISTS teams;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS events;
