package models

import (
	"time"

	"github.com/gofrs/uuid"
)

// Event Event model
type Event struct {
	TableName       struct{} `sql:"events,alias:event"`
	StartDate       time.Time
	EndDate         time.Time
	Matches         []Match
	ExternalID      string
	Name            string
	Logo            string
	Type            EventType
	Game            Game
	ID              uuid.NullUUID
	IsActive        bool `sql:",notnull"`
	IsAutogenerated bool `sql:",notnull"`
}

func (e *Event) GetID() string {
	return e.ID.UUID.String()
}

// Tests Equality of parts of the model that are not child objects or the ID
func (e *Event) EqualsShallow(b *Event) bool {
	return (e.StartDate.Equal(b.StartDate) &&
		e.EndDate.Equal(b.EndDate) &&
		e.ExternalID == b.ExternalID &&
		e.Name == b.Name &&
		e.Logo == b.Logo &&
		e.Type == b.Type &&
		e.Game == b.Game &&
		e.IsActive == b.IsActive &&
		e.IsAutogenerated == b.IsAutogenerated)
}
