package models

import (
	"time"

	"github.com/gofrs/uuid"
	"github.com/shopspring/decimal"
)

// Pool Represents a betting pool in colossus
type Pool struct {
	TableName            struct{} `sql:"pools,alias:pool"`
	LastSyncTime         *time.Time
	Legs                 []Leg
	Name                 string
	Game                 Game
	SyncedColossusStatus PoolStatus
	Type                 PoolType
	Guarantee            decimal.NullDecimal
	CarryIn              decimal.NullDecimal
	Allocation           decimal.NullDecimal
	UnitValue            decimal.NullDecimal
	MinUnitPerLine       decimal.NullDecimal
	MaxUnitPerLine       decimal.NullDecimal
	MinUnitPerTicket     decimal.NullDecimal
	MaxUnitPerTicket     decimal.NullDecimal
	Currency             PoolCurrency
	Note                 string
	ID                   uuid.NullUUID
	IsActive             bool `sql:",notnull"`
	IsAutogenerated      bool `sql:",notnull"`
	Consolations         []*ConsolationPrize
}

func (p *Pool) GetID() string {
	return p.ID.UUID.String()
}
